log_level: debug

home_assistant:
  host: hass.home.fossar.net:8123
  tls_enabled: true
  health_check_entities:
    - light.escalier_switch
    - light.poutre_dimmer
  subscribe_events:
    - state_changed
    - roku_command
  home_zone_name: home # Get latitude and longitude from configured zone

  # Or pass it as param with --senderConfig 'base64 encoded json' --senderConfig 'base64 encoded json' ...
senders:
  - name: telegram
    telegram:
      token: myBotToken
      chat_id: chatid

# This uses github.com/robfig/cron
crons:
  - expr: 0 1 * * *
    action: turn_off
    entities:
      - input_boolean.override_estrade_dehum

modules:
  - internetChecker:
      enabled: true
      interval: 2s
      ping_host: 8.8.8.8
      max_reboot_every: 180s
      restart_entity: switch.living_fbx
  - freshnessChecker:
      enabled: true
      name: Zigbee temp sensors
      interval: 10s
      freshness: 30s
      sender: telegram
      entities:
        - sensor.blue_hum_temp_last_seen
        - sensor.bedroom_hum_temp_last_seen
      template: |
        Les sensors Zigbee suivants n'ont pas donné de nouvelles depuis plus de {{ .Checker.Freshness }}:
        {{ JoinEntities .Entities "\n" "_last_seen" }}


triggers:
  - alert:
      trigger_entities:
        - binary_sensor.basement_leak_water_leak
      sender: telegram
      templates:
        binary_sensor.basement_leak_water_leak:
          msg_template: |
            {{- if .Event.NewState.Attributes.water_leak != .Event.OldState.Attributes.water_leak }}
              {{- if .Event.NewState.Attributes.water_leak }}
              ⚠ Dehumidifier full !
              {{- else }}
              Dehumidifier empty 👍 !
              {{- end }}
            {{- end }}
  - dehumidifier:
      enabled: false
      trigger_entities:
        - sensor.estrade_am2301_humidity
        - input_boolean.override_estrade_dehum
      switch_entity: switch.estrade_relay
      time_beg: 10:00:00
      time_end: 21:30:00
      threshold_min: 49
      threshold_max: 60
      manual_override: input_boolean.override_estrade_dehum
  - harmony:
      enabled: true
      trigger_events:
        - roku_command
      work_actions:
        - key: Up
          commands:
            - {entity: light.escalier_switch, service: toggle, only_dark: true}
            - {delay: 250ms}

