image:
  repository: nmaupu/gotomation
  tag: main
  pullPolicy: IfNotPresent

git:
  image: bitnami/git
  tag: 2.47.1
  gotomationConfig:
    repo: github.com/nmaupu/gotomation-config.git
    branch: master
    refreshIntervalSeconds: 60

# Existing secret containing extra configuration.
# Can be used to pass sensitive information as env vars
# Each secret entry is the env var name and its related value
existingSecretEnvVars: gotomation

gotomation:
  config:
    repo: https://github.com/nmaupu/gotomation-config
    branch: master
