timezone: Europe/Paris

image:
  repository: nmaupu/gotomation
  tag: main
  pullPolicy: IfNotPresent

git:
  image: nmaupu/argocd-cmp-jsonnet
  tag: 0.20.0
  pullPolicy: Always
  gotomationConfig:
    repo: github.com/nmaupu/gotomation-config.git
    branch: master
    refreshIntervalSeconds: 60

# Existing secret containing extra configuration.
# Can be used to pass sensitive information as env vars
# Each secret entry is the env var name and its related value
existingSecretEnvVars: gotomation

gotomation:
  config:
    repo: https://github.com/nmaupu/gotomation-config
    branch: master
